# Generated by Django 4.2.7 on 2023-11-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Токен для почты', 'verbose_name_plural': 'Токены для почты'},
        ),
    ]
