# Generated by Django 4.2.7 on 2023-12-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'Может блокировать пользователей сервиса')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
