# Generated by Django 4.2.7 on 2023-11-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала рассылки')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания рассылки')),
                ('frequency', models.CharField(choices=[('1/1', 'Раз в день'), ('1/7', 'Раз в неделю'), ('1/30', 'Раз в месяц')], default='1/1', max_length=4, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('CL', 'Завершено'), ('LC', 'Запущено'), ('CR', 'Создано')], default='CR', max_length=2, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Получатель')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Настройки рассылки.',
                'verbose_name_plural': 'Настройки рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время последней попытки')),
                ('attempt_status', models.IntegerField(blank=True, choices=[(1, 'Успешно'), (2, 'Неудачно'), (3, 'В процессе')], default=3, null=True, verbose_name='Статус попытки')),
                ('mail_server_response', models.CharField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Получатель')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Логи рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
    ]
