# Generated by Django 4.2.7 on 2023-11-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsettings_mailinglogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='attempt_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Успешно'), (2, 'Неудачно')], null=True, verbose_name='Статус попытки'),
        ),
    ]
