# Generated by Django 4.2.7 on 2023-12-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailingsettings_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_status', 'Может отключать рассылки')], 'verbose_name': 'Настройки рассылки.', 'verbose_name_plural': 'Настройки рассылок'},
        ),
    ]
