# Generated by Django 4.2.7 on 2023-11-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('cancel_published_status', 'Может отменять публикацию товара'), ('change_description', 'Может менять описание товара'), ('change_category', 'Может менять категорию товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
